# Generated by Django 5.0.6 on 2024-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=50)),
                ('notify_users', models.BooleanField(default=True)),
            ],
        ),
    ]
